# Generated by Django 2.2.3 on 2019-08-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="faucet",
            name="fee",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="faucet", name="sending_amount", field=models.DecimalField(decimal_places=15, max_digits=20)
        ),
    ]
