# Generated by Django 2.2.3 on 2019-08-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_auto_20190816_0711")]

    operations = [
        migrations.AlterField(
            model_name="faucet", name="fee", field=models.DecimalField(decimal_places=15, max_digits=40)
        ),
        migrations.AlterField(
            model_name="faucet", name="sending_amount", field=models.DecimalField(decimal_places=15, max_digits=40)
        ),
    ]
