# Generated by Django 2.2.4 on 2019-09-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0003_auto_20190816_0730")]

    operations = [
        migrations.RemoveField(model_name="faucet", name="visible"),
        migrations.RemoveField(model_name="faucet", name="wallet_address"),
        migrations.RemoveField(model_name="faucet", name="wallet_id"),
    ]
